services:
  laravel-docker:
    container_name: WorkApp
    build: .
    volumes:
      - ./WorkApp:/var/www/html
    ports:
      - 9000:80

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: WorkApp
    ports:
      - "3306:3306"
  
  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - 9001:80
    environment:
      - PMA_ARBITRARY=1

  mailhog:
    image: mailhog/mailhog
    ports:
        - 8025:8025